### ISSUE TITLE
suggestions for added features

### ISSUE THREAD

**Issue by SilverfishVR** [AleziaKurdis/materialDataCreator#1]
Hi, I tested this out today and I really like the idea 👍 and I have suggestions to make me like it even more 😄 :

- Add the `cullFaceMode` property [CULL_BACK(default), CULL_FRONT, CULL_NONE], very handy for adding double sided rendering to fbx.

- Add the `opacityMapMode` property [OPACITY_MAP_MASK, OPACITY_MAP_BLEND, OPACITY_MAP_OPAQUE]
I think, setting this property also means you don’t have to add the `opacityMap` property to get opacity to work.

- Optionally, add the `opacityCutoff` property [0,1f], which is valid when using OPACITY_MAP_MASK.

- While getting the material from a model may be problematic due to embedded textures you could still import the material properties from a material entity into the app, perhaps even do live update on the material entity so you can modify a material with it even if it already parented to a model.

**Comment by AleziaKurdis** [comment]
cullFaceMode added.

![image](https://user-images.githubusercontent.com/60075796/110416480-cf1e8900-8061-11eb-8ec3-1990570f282c.png)


I vulgarized it a bit since cullFaceMode is a bit obscure. (to me at least)

**Comment by AleziaKurdis** [comment]
**opacityMapMode** and **opacityCutoff** added.

![image](https://user-images.githubusercontent.com/60075796/110581958-76baba80-8139-11eb-9199-2003128acd1c.png)

That will be that for now.
I think this will be already useful.

Live update on parented entities would be interesting. But it's not a quick win. That will be for a next iteration.

**Comment by SilverfishVR** [comment]
I agree, it's very useful and works well as is. closing this issue
